export const currencyList: {
  name: string;
  iso: string;
  nickname: string;
}[] = [
  { name: "Ringgit Malaysia", iso: "MYR", nickname: "RM" }, 
  { name: "Singapore Dollar", iso: "SGD", nickname: "SGD" }, 
  { name: "Baht", iso: "THB", nickname: "THB" }, 
  { name: "Yuan Renminbi", iso: "CNY", nickname: "CNY" }, 
  { name: "Hong Kong Dollar", iso: "HKD", nickname: "HKD" }, 
  { name: "Indian Rupee", iso: "INR", nickname: "INR" }, 
  { name: "Rupiah", iso: "IDR", nickname: "IDR" }, 
  { name: "Won", iso: "KRW", nickname: "KRW" }, 
  { name: "United States Dollar", iso: "USD", nickname: "USD" }, 
  { name: "European Euro", iso: "EUR", nickname: "EUR" }, 
  { name: "Australian Dollar", iso: "AUD", nickname: "AUD" }, 
  { name: "Norwegian Krone", iso: "NOK", nickname: "NOK" }, 
  { name: "Brazilian Real", iso: "BRL", nickname: "BRL" }, 
  { name: "Bulgarian Lev", iso: "BGN", nickname: "BGN" }, 
  { name: "Canadian Dollar", iso: "CAD", nickname: "CAD" }, 
  { name: "New Zealand Dollar", iso: "NZD", nickname: "NZD" }, 
  { name: "Czech Koruna", iso: "CZK", nickname: "CZK" }, 
  { name: "Danish Krone", iso: "DKK", nickname: "DKK" }, 
  { name: "Pound Sterling", iso: "GBP", nickname: "GBP" }, 
  { name: "Forint", iso: "HUF", nickname: "HUF" }, 
  { name: "Iceland Krona", iso: "ISK", nickname: "ISK" }, 
  { name: "New Israeli Sheqel", iso: "ILS", nickname: "ILS" }, 
  { name: "Rand", iso: "ZAR", nickname: "ZAR" }, 
  { name: "Swiss Franc", iso: "CHF", nickname: "CHF" }, 
  { name: "Philippine Peso", iso: "PHP", nickname: "PHP" }, 
  { name: "Zloty", iso: "PLN", nickname: "PLN" }, 
  { name: "Romanian Leu", iso: "RON", nickname: "RON" }, 
  { name: "Swedish Krona", iso: "SEK", nickname: "SEK" }, 
  { name: "Turkish Lira", iso: "TRY", nickname: "TRY" }, 
  // { name: "Saudi Riyal", iso: "SAR", nickname: "SAR" },
  // { name: "Afghani", iso: "AFN", nickname: "AFN" },
  // { name: "Lek", iso: "ALL", nickname: "ALL" },
  // { name: "Algerian Dinar", iso: "DZD", nickname: "DZD" },
  // { name: "Kwanza", iso: "AOA", nickname: "AOA" },
  // { name: "East Caribbean Dollar", iso: "XCD", nickname: "XCD" },
  // { name: "Argentine Peso", iso: "ARS", nickname: "ARS" },
  // { name: "Armenian Dram", iso: "AMD", nickname: "AMD" },
  // { name: "Aruban Florin", iso: "AWG", nickname: "AWG" },
  // { name: "Azerbaijanian Manat", iso: "AZN", nickname: "AZN" },
  // { name: "Bahamian Dollar", iso: "BSD", nickname: "BSD" },
  // { name: "Bahraini Dinar", iso: "BHD", nickname: "BHD" },
  // { name: "Taka", iso: "BHD", nickname: "BHD" },
  // { name: "Barbados Dollar", iso: "BBD", nickname: "BBD" },
  // { name: "Belarussian Ruble", iso: "BYN", nickname: "BYN" },
  // { name: "Belize Dollar", iso: "BYN", nickname: "BYN" },
  // { name: "Bermudian Dollar", iso: "BMD", nickname: "BMD" },
  // { name: "Ngultrum", iso: "BTN", nickname: "BTN" },
  // { name: "Boliviano", iso: "INR", nickname: "INR" },
  // { name: "Mvdol", iso: "BOV", nickname: "BOV" },
  // { name: "Convertible Mark", iso: "BAM", nickname: "BAM" },
  // { name: "Pula", iso: "BWP", nickname: "BWP" },
  // { name: "Brunei Dollar", iso: "BND", nickname: "BND" },
  // { name: "Burundi Franc", iso: "BIF", nickname: "BIF" },
  // { name: "Cabo Verde Escudo", iso: "CVE", nickname: "CVE" },
  // { name: "Riel", iso: "KHR", nickname: "KHR" },
  // { name: "CFA Franc BEAC", iso: "XAF", nickname: "XAF" },
  // { name: "Cayman Islands Dollar", iso: "KYD", nickname: "KYD" },
  // { name: "Unidad de Fomento", iso: "CLF", nickname: "CLF" },
  // { name: "Chilean Peso", iso: "CLP", nickname: "CLP" },
  // { name: "Colombian Peso", iso: "COP", nickname: "COP" },
  // { name: "Unidad de Valor Real", iso: "COU", nickname: "COU" },
  // { name: "Comoro Franc", iso: "KMF", nickname: "KMF" },
  // { name: "Congolese Franc", iso: "CDF", nickname: "CDF" },
  // { name: "Costa Rican Colon", iso: "CRC", nickname: "CRC" },
  // { name: "Kuna", iso: "HRK", nickname: "HRK" },
  // { name: "Peso Convertible", iso: "CUC", nickname: "CUC" },
  // { name: "Cuban Peso", iso: "	CUP", nickname: "CUP" },
  // { name: "Netherlands Antillean Guilder", iso: "ANG", nickname: "ANG" },
  // { name: "CFA Franc BCEAO", iso: "XOF", nickname: "XOF" },
  // { name: "Djibouti Franc", iso: "DJF", nickname: "DJF" },
  // { name: "Dominican Peso", iso: "DOP", nickname: "DOP" },
  // { name: "Egyptian Pound", iso: "EGP", nickname: "EGP" },
  // { name: "El Salvador Colon", iso: "SVC", nickname: "SVC" },
  // { name: "Nakfa", iso: "ERN", nickname: "ERN" },
  // { name: "Ethiopian Birr", iso: "ETB", nickname: "ETB" },
  // { name: "Falkland Islands Pound", iso: "FKP", nickname: "FKP" },
  // { name: "Fiji Dollar", iso: "FJD", nickname: "FJD" },
  // { name: "CFP Franc", iso: "XPF", nickname: "XPF" },
  // { name: "Dalasi", iso: "GMD", nickname: "GMD" },
  // { name: "Lari", iso: "GEL", nickname: "GEL" },
  // { name: "Ghana Cedi", iso: "GHS", nickname: "GHS" },
  // { name: "Gibraltar Pound", iso: "GIP", nickname: "GIP" },
  // { name: "Quetzal", iso: "GTQ", nickname: "GTQ" },
  // { name: "Guinea Franc", iso: "GNF", nickname: "GNF" },
  // { name: "Guyana Dollar", iso: "GYD", nickname: "GYD" },
  // { name: "Gourde", iso: "HTG", nickname: "HTG" },
  // { name: "Lempira", iso: "HNL", nickname: "HNL" },
  // { name: "Special Drawing Right", iso: "XDR", nickname: "XDR" },
  // { name: "Iranian Rial", iso: "IRR", nickname: "IRR" },
  // { name: "Iraqi Dinar", iso: "IQD", nickname: "IQD" },
  // { name: "Jamaican Dollar", iso: "JMD", nickname: "JMD" },
  // { name: "Yen", iso: "JPY", nickname: "JPY" }, //
  // { name: "Jordanian Dinar", iso: "JOD", nickname: "JOD" },
  // { name: "Tenge", iso: "KZT", nickname: "KZT" },
  // { name: "Kenyan Shilling", iso: "KES", nickname: "KES" },
  // { name: "North Korean Won", iso: "KPW", nickname: "KPW" },
  // { name: "Kuwaiti Dinar", iso: "KWD", nickname: "KWD" },
  // { name: "Som", iso: "KGS", nickname: "KGS" },
  // { name: "Kip", iso: "LAK", nickname: "LAK" },
  // { name: "Lebanese Pound", iso: "LBP", nickname: "LBP" },
  // { name: "Loti", iso: "LSL", nickname: "LSL" },
  // { name: "Liberian Dollar", iso: "LRD", nickname: "LRD" },
  // { name: "Libyan Dinar", iso: "LYD", nickname: "LYD" },
  // { name: "Pataca", iso: "MOP", nickname: "MOP" },
  // { name: "Malagasy Ariary", iso: "MGA", nickname: "MGA" },
  // { name: "Kwacha", iso: "MWK", nickname: "MWK" },
  // { name: "Rufiyaa", iso: "MVR", nickname: "MVR" },
  // { name: "Ouguiya", iso: "MRU", nickname: "MRU" },
  // { name: "Mauritius Rupee", iso: "MUR", nickname: "MUR" },
  // { name: "ADB Unit of Account", iso: "XUA", nickname: "XUA" },
  // { name: "Mexican Peso", iso: "MXN", nickname: "MXN" }, //
  // { name: "Mexican Unidad de Inversion (UDI)", iso: "MXV", nickname: "MXV" },
  // { name: "Moldovan Leu", iso: "MDL", nickname: "MDL" },
  // { name: "Tugrik", iso: "MNT", nickname: "MNT" },
  // { name: "Moroccan Dirham", iso: "MAD", nickname: "MAD" },
  // { name: "Mozambique Metical", iso: "MZN", nickname: "MZN" },
  // { name: "Kyat", iso: "MMK", nickname: "MMK" },
  // { name: "Namibia Dollar", iso: "NAD", nickname: "NAD" },
  // { name: "Nepalese Rupee", iso: "NPR", nickname: "NPR" },
  // { name: "CFP Franc", iso: "XPF", nickname: "XPF" },
  // { name: "Cordoba Oro", iso: "NIO", nickname: "NIO" },
  // { name: "Naira", iso: "NGN", nickname: "NGN" },
  // { name: "Rial Omani", iso: "OMR", nickname: "OMR" },
  // { name: "Balboa", iso: "PAB", nickname: "PAB" },
  // { name: "Kina", iso: "PGK", nickname: "PGK" },
  // { name: "Guarani", iso: "PYG", nickname: "PYG" },
  // { name: "Nuevo Sol", iso: "PEN", nickname: "PEN" },
  // { name: "Qatari Rial", iso: "QAR", nickname: "QAR" },
  // { name: "Denar", iso: "MKD", nickname: "MKD" },
  // { name: "Russian Ruble", iso: "RUB", nickname: "RUB" },
  // { name: "Rwanda Franc", iso: "RWF", nickname: "RWF" },
  // { name: "Saint Helena Pound", iso: "SHP", nickname: "SHP" },
  // { name: "Tala", iso: "WST", nickname: "WST" },
  // { name: "Dobra", iso: "STN", nickname: "STN" },
  // { name: "Serbian Dinar", iso: "RSD", nickname: "RSD" },
  // { name: "Seychelles Rupee", iso: "SCR", nickname: "SCR" },
  // { name: "Leone", iso: "SLL", nickname: "SLL" },
  // { name: "Sucre", iso: "XSU", nickname: "XSU" },
  // { name: "Solomon Islands Dollar", iso: "SBD", nickname: "SBD" },
  // { name: "Somali Shilling", iso: "SOS", nickname: "SOS" },
  // { name: "South Sudanese Pound", iso: "SSP", nickname: "SSP" },
  // { name: "Sri Lanka Rupee", iso: "LKR", nickname: "LKR" },
  // { name: "Sudanese Pound", iso: "SDG", nickname: "SDG" },
  // { name: "Surinam Dollar", iso: "SRD", nickname: "SRD" },
  // { name: "Lilangeni", iso: "SZL", nickname: "SZL" },
  // { name: "WIR Euro", iso: "CHE", nickname: "CHE" },
  // { name: "Swiss Franc", iso: "CHF", nickname: "CHF" },
  // { name: "WIR Franc", iso: "CHF", nickname: "CHF" },
  // { name: "Syrian Pound", iso: "SYP", nickname: "SYP" },
  // { name: "New Taiwan Dollar", iso: "TWD", nickname: "TWD" },
  // { name: "Somoni", iso: "TJS", nickname: "TJS" },
  // { name: "Tanzanian Shilling", iso: "TZS", nickname: "TZS" },
  // { name: "Pa’anga", iso: "TOP", nickname: "TOP" },
  // { name: "Trinidad and Tobago Dollar", iso: "TTD", nickname: "TTD" },
  // { name: "Tunisian Dinar", iso: "TND", nickname: "TND" },
  // { name: "Turkmenistan New Manat", iso: "TMT", nickname: "TMT" },
  // { name: "Uganda Shilling", iso: "UGX", nickname: "UGX" },
  // { name: "Hryvnia", iso: "UAH", nickname: "UAH" },
  // { name: "UAE Dirham", iso: "AED", nickname: "AED" },
  // { name: "Uruguay Peso en Unidades Indexadas", iso: "UYI", nickname: "UYI" },
  // { name: "Peso Uruguayo", iso: "UYU", nickname: "UYU" },
  // { name: "Uzbekistan Sum", iso: "UZS", nickname: "UZS" },
  // { name: "Vatu", iso: "VUV", nickname: "VUV" },
  // { name: "Bolivar", iso: "VEF", nickname: "VEF" },
  // { name: "Dong", iso: "VND", nickname: "VND" },
  // { name: "CFP Franc", iso: "XPF", nickname: "XPF" },
  // { name: "Moroccan Dirham", iso: "MAD", nickname: "MAD" },
  // { name: "Yemeni Rial", iso: "YER", nickname: "YER" },
  // { name: "Zambian Kwacha", iso: "ZMW", nickname: "ZMW" },
  // { name: "Zimbabwe Dollar", iso: "ZWL", nickname: "ZWL" },
];
