require("dotenv").config();

export default function getTransactionCategoryAsset() {
  const s3Path = `${process.env.S3_BUCKET_BASE_URL}/propermoney/transaction_category_icon/`;
  const result = {
    icons: [
      `${s3Path}GasStationIcon.png`,
      `${s3Path}RestaurantIcon.png`,
      `${s3Path}ParkingIcon.png`,
      `${s3Path}HomeIcon.png`,
      `${s3Path}PacifierIcon.png`,
      `${s3Path}EnergyIcon.png`,
      `${s3Path}DrinkIcon.png`,
      `${s3Path}CoffeeIcon.png`,
      `${s3Path}BankIcon.png`,
      `${s3Path}LaundryIcon.png`,
      `${s3Path}ClothesIcon.png`,
      `${s3Path}TrainIcon.png`,
      `${s3Path}CarIcon.png`,
      `${s3Path}BreadIcon.png`,
      `${s3Path}HomeSalonIcon.png`,
      `${s3Path}PlaneIcon.png`,
      `${s3Path}MedicalIcon.png`,
      `${s3Path}BeerIcon.png`,
      `${s3Path}ToolsIcon.png`,
      `${s3Path}PetIcon.png`,
      `${s3Path}MovieIcon.png`,
      `${s3Path}ComputerIcon.png`,
      `${s3Path}PhoneIcon.png`,
      `${s3Path}GymIcon.png`,
      `${s3Path}UserIcon.png`,
      `${s3Path}BedIcon.png`,
      `${s3Path}MusicIcon.png`,
      `${s3Path}LoveIcon.png`,
      `${s3Path}GiftIcon.png`,
      `${s3Path}ShieldIcon.png`,
      `${s3Path}FootballIcon.png`,
      `${s3Path}EducationIcon.png`,
      `${s3Path}BookIcon.png`,
      `${s3Path}PriceTagIcon.png`,
      `${s3Path}MoneyIcon.png`,
      `${s3Path}MotorcycleIcon.png`,
    ],
    backgroundColors: [
      `#F8A90B`,
      `#F8CB20`,
      `#BDD73E`,
      `#78C44D`,
      `#1EB975`,
      `#53C7A7`,
      `#53C2B8`,
      `#2CA5B1`,
      `#E0625C`,
      `#B2543C`,
      `#B5764F`,
      `#DF6D18`,
      `#EA8D3F`,
      `#DE8C23`,
      `#A88952`,
      `#F19910`,
      "#6F42C6",
      "#E768F0",
      "#EF629C",
      "#E75F73",
      `#1895C7`,
      `#3FA7E8`,
      `#3E78AB`,
      `#5C93C2`,
      `#7286B7`,
      `#5F6163`,
      `#566B83`,
      `#777793`,
    ],
  };
  return result;
}
